workflows:
  android-firebase-workflow:
    name: Nurexus Android Firebase Deploy
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - publish
      vars:
        FIREBASE_APP_ID: "1:56974215210:android:41b1d89410e53fdb1c1b53"
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Android APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      firebase:
        service_account: $FIREBASE_SERVICE_ACCOUNT_JSON
        android:
          app_id: $FIREBASE_APP_ID
          groups:
            - nurexus
